const medicinalPlantList = [
    "neem", "tulasi", "aloe vera", "ashwagandha", "turmeric", 
    "ginger", "garlic", "mint", "lavender", "papaya", "henna",
    "amla", "brahmi", "eucalyptus", "sandalwood", "lemongrass",
    "holy basil", "cinnamon", "clove", "fennel", "ginseng",
    "chamomile", "echinacea", "valerian", "calendula", "peppermint",
    "rosemary", "thyme", "oregano", "sage", "dandelion",
    "licorice", "milk thistle", "hawthorn", "passionflower",
    "slippery elm", "goldenseal", "catnip", "burdock", "yarrow",
    "comfrey", "goldenrod", "marshmallow root", "red clover", "st. john's wort",
    "ginkgo biloba", "kava kava", "sarsaparilla", "turmeric", "willow bark",
    "ashoka", "bael", "haritaki", "jatamansi", "manjistha", "shatavari", "vidanga",
    "basil", "coriander", "cumin", "fennel", "fenugreek", "mustard", "saffron",
    "aloe", "anise", "angelica", "barberry", "black cohosh", "blueberry",
    "chaste tree", "cranberry", "elderberry", "feverfew", "hawthorn", "hemp",
    "honeysuckle", "juniper", "lavender", "lemon balm", "licorice root",
    "marjoram", "meadowsweet", "mullein", "nettle", "passionflower", "peppermint",
    "plantain", "pomegranate", "red raspberry", "sage", "skullcap",
    "slippery elm", "spearmint", "valerian root", "white willow", "witch hazel",
    "yohimbe", "zinc"
];

const medicinalList = [
  // 🌿 Medicinal Plants & Herbs
  "neem",
  "tulsi",
  "aloe vera",
  "ashwagandha",
  "turmeric",
  "ginger",
  "garlic",
  "mint",
  "lavender",
  "papaya",
  "henna",
  "amla",
  "brahmi",
  "eucalyptus",
  "sandalwood",
  "lemongrass",
  "cinnamon",
  "clove",
  "fennel",
  "ginseng",
  "chamomile",
  "echinacea",
  "valerian",
  "calendula",
  "peppermint",
  "rosemary",
  "thyme",
  "oregano",
  "sage",
  "dandelion",
  "licorice",
  "milk thistle",
  "hawthorn",
  "passionflower",
  "slippery elm",
  "goldenseal",
  "comfrey",
  "yarrow",
  "marshmallow root",
  "red clover",
  "ginkgo biloba",
  "kava kava",
  "sarsaparilla",
  "willow bark",
  "ashoka",
  "bael",
  "haritaki",
  "jatamansi",
  "manjistha",
  "shatavari",
  "vidanga",
  "basil",
  "coriander",
  "cumin",
  "fenugreek",
  "mustard",
  "saffron",
  "anise",
  "angelica",
  "barberry",
  "black cohosh",
  "blueberry",
  "chaste tree",
  "cranberry",
  "elderberry",
  "feverfew",
  "hemp",
  "honeysuckle",
  "juniper",
  "lemon balm",
  "marjoram",
  "meadowsweet",
  "mullein",
  "nettle",
  "plantain",
  "pomegranate",
  "red raspberry",
  "skullcap",
  "spearmint",
  "white willow",
  "witch hazel",
  "euphorbia hirta",
  "guava",
  "boldo",
  "guaco",

  // 💊 Vitamins
  "vitamin A",
  "vitamin B1 (thiamine)",
  "vitamin B2 (riboflavin)",
  "vitamin B3 (niacin)",
  "vitamin B5 (pantothenic acid)",
  "vitamin B6",
  "vitamin B7 (biotin)",
  "vitamin B9 (folate)",
  "vitamin B12",
  "vitamin C",
  "vitamin D",
  "vitamin E",
  "vitamin K",

  // 🧂 Minerals
  "calcium",
  "magnesium",
  "potassium",
  "sodium",
  "iron",
  "zinc",
  "copper",
  "manganese",
  "selenium",
  "chromium",
  "iodine",
  "phosphorus",
  "fluoride"
];


const isMedicinal = (plantName) => {
    if (!plantName || typeof plantName !== 'string') return false;
    return medicinalPlantList.includes(plantName.trim().toLowerCase());
};

module.exports = { isMedicinal };